config/routes.rb
Rails.application.routes.draw do
	root to: 'labs#index'
	resources :scientists
	resources :labs
	get '/login', to: 'sessions#new'
	get '/logout', to: 'sessions#destroy'
	get '/labs/:id/zerg/new', to: 'zerg#new', as: 'zergs'
	get '/labs/:id/zerg/:specie', to: 'zerg#index' 
	post '/sessions', to: 'sessions#create'
	post '/labs/:id/zerg/new', to: 'zerg#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lab.rb
class Lab < ApplicationRecord
	validates :name, presence: true
	has_many :scientists
	has_many :zerg
end

app/models/scientist.rb
class Scientist < ApplicationRecord
	has_secure_password
	validates :username, uniqueness: true, presence: true
	belongs_to :lab, optional: true
	def self.confirm(params)
		@user = Scientist.find_by({username: params[:username]})
		@user ? @user.authenticate(params[:password]) : false
	end
end

app/models/zerg.rb
class Zerg < ApplicationRecord
  belongs_to :lab, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def require_login
    unless current_user
      #send an http response to stop program execution
      redirect_to root_path
    end
  end
  # def require_authorization
  # 	if current_user

  # 	else
  # 		redi
  # end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
	def index
		@labs = Lab.all
	end
	def show
		@lab = Lab.find_by_id(params[:id])
	end
end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
	before_action :require_login, only: :show
	def index
		@scientists = Scientist.all
	end

	def new
		@scientist = Scientist.new
		p "Hello"
	end

	def create
		@scientist = Scientist.create(user_params)
		login(@scientist)
		redirect_to @scientist
	end

	def show
		@scientist = Scientist.find_by_id(params[:id])
	end

	private
	def user_params
		params.require(:scientist).permit(:email, :password, :username, :first_name, :last_name)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@scientist = Scientist.new
	end

	def create
		user_params = params.require(:scientist).permit(:username, :password)
		@user = Scientist.confirm(user_params)
		if @user
			login(@user)
			flash[:notice] = "Successfully logged in."
			redirect_to @user
		else
			flash[:error] = "Incorrect email or password."
			redirect_to login_path
		end
	end

	def destroy
      logout # coming soon in SessionsHelper
      redirect_to root_path
    end
end

app/controllers/zerg_controller.rb
class ZergController < ApplicationController
	def new
		@zerg = Zerg.new
	end
	def index
		@zerg = Zerg.where({specie: params[:specie], lab: findLab})
	end
	def create
		@zerg = Zerg.create(zergParams)
		@zerg.lab_id = params[:id]
		@zerg.save
		redirect_to '/labs/' + params[:id]
	end

	private

	def findLab
		lab = Lab.find_by_id(params[:id])
		return lab
	end

	def zergParams
		params.require(:zerg).permit(:identification, :specie, :strain, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/scientists_helper.rb
module ScientistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:scientist_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= Scientist.find_by_id(session[:scientist_id])
  end

  def logout
  	@current_user = session[:scientist_id] = nil
  end

end

app/helpers/zerg_helper.rb
module ZergHelper
end

app/views/labs/index.html.erb
<h2>
	Terran Dominion Labs
</h2>

<% @labs.each do |lab| %>
	<div><h3><%= link_to lab.name, lab_path(lab) %></h3></div> <br>
<% end %>

app/views/labs/show.html.erb
<h2><%= @lab.name %></h2>
<div style="float: left; width: auto;"><%= button_to "Add Scientist", '#', method: :get %> </div>
<%= button_to "Add Zerg Specimen", zergs_path, method: :get %>

<h3>Scientists working in this lab: </h3>
<% @lab.scientists.each do |dr| %>
	<div>Dr. <%= dr.first_name %> <%= dr.last_name %> </div>
<% end %>

<h3>Zerg Specimen in this lab</h3>
<p>There are currently <%= @lab.zerg.length %> housed in this lab!</p> 
<!-- TODO: List the Zerg Specimen Here -->
<% ["Zergling", "Roach", "Hydralisk"].each do |type| %>
	<% if @lab.zerg.where({specie: type}).length > 0 %>
		<div><%= link_to type, '/labs/' + params[:id] + '/zerg/' + type %>: <%= @lab.zerg.where({specie: type}).length %> specimans</div>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZergLab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
      <% if current_user %>
        <li><%= link_to "Profile", scientist_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_scientist_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
  </ul>

  <% flash.each do |name, msg| %>
    <p>
      <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/scientists/index.html.erb
<h1>List of Scientists</h1>
<div>
There are currently <%= @scientists.length %> scientists working on Project Blackstone!
</div>

app/views/scientists/new.html.erb
Sign Up

<%= form_for @scientist do |f| %>
  <div>
    <%= f.text_field :username, placeholder: "username" %>
  </div>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/scientists/show.html.erb
<div>
  Greetings,  esteemed collegue Dr. <%= @scientist.last_name %>!
</div>

app/views/zerg/index.html.erb
<h2> <%= params[:specie] %> </h2>
<% @zerg.each do |z| %>
	<div>
		Identification: <%= z.identification %> <br>
		Type: <%= z.specie %> <br>
		Strain: <%= z.strain %> <br>
	</div> 
	<%= image_tag(z.image, size: '200x200') %>
	
<% end %>

app/views/zerg/new.html.erb
New Zerg Speciman

<%= form_for @zerg do |z| %>
  <div>
    <%= z.text_field :identification, placeholder: "Zerg ID" %>
  </div>
  <div>
    <%= z.text_field :specie, placeholder: "Zerg Species" %>
  </div>
  <div>
    <%= z.text_field :strain, placeholder: "Zerg Strain" %>
  </div>
  <div>
    <%= z.text_field :image, placeholder: "Image" %>
  </div>
  
  <%= z.submit "Submit Speciman" %>
<% end %>